apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keybuzz-api-ingress
  namespace: keybuzz
  annotations:
    nginx.ingress.kubernetes.io/upstream-vhost: keybuzz-api.keybuzz.svc.cluster.local
spec:
  ingressClassName: nginx
  rules:
  - host: platform-api.keybuzz.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keybuzz-api
            port:
              number: 8080

